FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

# Instalar dependencias con --frozen-lockfile
RUN pnpm install --frozen-lockfile

COPY . .


EXPOSE 3145

CMD ["pnpm", "start:dev"]
