FROM mcr.microsoft.com/playwright:v1.59.1-jammy

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3145

CMD ["pnpm", "start:dev"]
